const products = [
    { name: "Nazgul Calendario Perpetuo 3D", type: "Figura de acción", origin: "El señor de los anillos", image: "", price: 30, top: 1, links: [
        "https://www.amazon.es/Calendario-perpetuo-Se%C3%B1or-los-anillos/dp/B0DCVQV2KM",
        "https://www.fnac.es/CAL-PERPETUO-3D-ESDLA-Goodies-Otro-producto-derivado/a11024766"
    ] },
    { name: '"Rechicero" editorial Debolsillo (novela Mundodisco)', type: "Libro", origin: "Terry Pratchett", image: "", price: 0, top: 1, links: [] },
    { name: '"Brujerías" editorial Debolsillo (novela Mundodisco)', type: "Libro", origin: "Terry Pratchett", image: "", price: 0, top: 1, links: [] },
    { name: '"Pirómides" editorial Debolsillo (novela Mundodisco)', type: "Libro", origin: "Terry Pratchett", image: "", price: 0, top: 1, links: [] },
    { name: 'Vivi 28cm aprox.', type: "Peluche", origin: "Final Fantasy IX", image: "", price: 0, top: 1, links: [] },
    { name: "Gen asagiri", type: "Figura de acción", origin: "Dr. Stone", image: "", price: 0, top: 1, links: [] },
    { name: "Señor de los Nazgul / Rey Brujo", type: "Figura de acción", origin: "El señor de los anillos", image: "", price: 0, top: 1, links: [] },
    { name: "Brook", type: "Figura de acción", origin: "One Piece", image: "", price: 0, top: 1, links: [] },
    { name: "Suika", type: "Figura de acción", origin: "Dr. Stone", image: "", price: 0, top: 1, links: [] },
    { name: "La herencia de la tía Ágata", type: "Juego de mesa", origin: "Bizak", image: "", price: 0, top: 1, links: [] },
    { name: "El señor de los anillos: Aventura hacia el Monte del Destino", type: "Juego de mesa", origin: "Devir", image: "", price: 0, top: 1, links: [] },
    { name: "Pyramid Head", type: "Figura de acción", origin: "Silent Hill 2", image: "", price: 0, top: 1, links: [] },
    { name: "Qiqi", type: "Figura de acción", origin: "Genshin Impact", image: "", price: 0, top: 1, links: [] },
    { name: "Vamos a pegarnos con espadas de mentira", type: "Juego de mesa", origin: "Exploding Kittens", image: "", price: 0, top: 1, links: [] },
    { name: "Yo Soy Tu Peli", type: "Juego de mesa", origin: "HelloFun!", image: "", price: 0, top: 1, links: [] },
    { name: "¿Quién es quién? Super Mario", type: "Juego de mesa", origin: "¿Quién es quién?", image: "", price: 0, top: 1, links: [] },
    { name: 'Elemento electro o dendro (grande 50cm)', type: "Peluche", origin: "Genshin Impact", image: "", price: 0, top: 1, links: [] },
    { name: "Animal Crossing: New Horizons", type: "Videojuego", origin: "Nintendo Switch", image: "", price: 0, top: 1, links: [] },
    { name: "Zelda: Breath of the wild", type: "Videojuego", origin: "Nintendo Switch", image: "", price: 0, top: 1, links: [] },
    { name: "Street Fighter VI", type: "Videojuego", origin: "Xbox Series X", image: "", price: 0, top: 1, links: [] },
    { name: "The Boys (cómic de Garth Ennis y Darick Robertson)", type: "Cómic", origin: "Garth Ennis, Darick Robertson", image: "", price: 0, top: 1, links: [] },
    { name: "Piratas del Caribe: La maldición de la perla negra", type: "Blu-ray", origin: "Película", image: "", price: 0, top: 1, links: [] },
    { name: "Piratas del Caribe: El cofre del hombre muerto", type: "Blu-ray", origin: "Película", image: "", price: 0, top: 1, links: [] },
    { name: "Piratas del Caribe: En el fin del mundo", type: "Blu-ray", origin: "Película", image: "", price: 0, top: 1, links: [] },
    { name: "Nintendo Switch Sports", type: "Videojuego", origin: "Nintendo Switch", image: "", price: 0, top: 1, links: [] },
    { name: "Paper Mario: La puerta milenaria", type: "Videojuego", origin: "Nintendo Switch", image: "", price: 0, top: 1, links: [] },
    { name: "Asesinato en el Orient Express", type: "Blu-ray", origin: "Película de 1974", image: "", price: 0, top: 1, links: [] },
    { name: "Alan Wake II DLC", type: "Videojuego", origin: "Xbox Series X", image: "", price: 0, top: 1, links: [] },
    { name: "Clásicos", type: "Blu-ray", origin: "Película", image: "", price: 0, top: 1, links: [] },
    { name: "Voces en la oscuridad (manga de Junji Ito)", type: "Cómic", origin: "Junji Ito", image: "", price: 0, top: 1, links: [] },
    { name: "Black Paradox (manga de Junji Ito)", type: "Cómic", origin: "Junji Ito", image: "", price: 0, top: 1, links: [] },
    { name: "InuYasha", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Yu Yu Hakusho", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Ranma 1/2", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Slam Dunk", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Another", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Sakura Card Captor", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "Utena", type: "Blu-ray", origin: "Anime", image: "", price: 0, top: 1, links: [] },
    { name: "DaVinci Resolve Studio", type: "Software", origin: "Licencia", image: "", price: 0, top: 1, links: [] }
];